<?php
/**
 * add_transaction.php
 *
 * This file provides a form for adding new transactions and processes the form submission.
 * It integrates with the database to save transaction details and log audit trail entries.
 */

session_start();

// Check if the user is logged in. If not, redirect to the login page.
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

// Include database connection and necessary classes
require_once 'db_connect.php';
require_once 'User.php';
require_once 'Client.php';
require_once 'Transaction.php';

// Initialize handlers
$userHandler = new User($pdo);
$clientHandler = new Client($pdo);
$transactionHandler = new Transaction($pdo);

// Fetch logged-in user's details
$userId = $_SESSION['user_id'];
$currentUser = $userHandler->getUserById($userId);

// Fetch clients for the dropdown
$clients = $clientHandler->getClientsByUserId($userId);

$errorMessage = '';
$successMessage = '';

// Handle form submission
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $transactionDate = trim($_POST['transaction_date'] ?? '');
    $description = trim($_POST['description'] ?? '');
    $category = trim($_POST['category'] ?? '');
    $amount = filter_var($_POST['amount'] ?? '', FILTER_VALIDATE_FLOAT);
    $currency = trim($_POST['currency'] ?? '');
    $transactionType = trim($_POST['transaction_type'] ?? '');
    $clientId = filter_var($_POST['client_id'] ?? '', FILTER_VALIDATE_INT);

    // Basic validation
    if (empty($transactionDate) || empty($description) || empty($category) || $amount === false || $amount <= 0 || empty($currency) || empty($transactionType)) {
        $errorMessage = "Please fill in all required fields correctly.";
    } elseif (!in_array($transactionType, ['Income', 'Expense', 'Transfer'])) {
        $errorMessage = "Invalid transaction type selected.";
    } elseif ($clientId !== false && $clientId !== null) {
        // If a client ID is provided, verify it belongs to the user
        $clientExists = $clientHandler->getClientByIdAndUserId($clientId, $userId);
        if (!$clientExists) {
            $errorMessage = "Selected client is invalid or does not belong to your account.";
            $clientId = null; // Reset to null if invalid
        }
    } else {
        $clientId = null; // Ensure it's null if no client was selected or invalid
    }

    if (empty($errorMessage)) {
        // Generate a placeholder blockchain hash for new transactions
        // In a real application, this would be generated by your blockchain integration
        $blockchainHash = '0x' . bin2hex(random_bytes(32)); // Example 64-char hex hash

        // Add the transaction
        $addSuccess = $transactionHandler->addTransaction(
            $userId,
            $transactionDate,
            $description,
            $category,
            $amount,
            $currency,
            $transactionType,
            $clientId,
            $blockchainHash,
            'Pending' // New transactions start as pending verification
        );

        if ($addSuccess) {
            $successMessage = "Transaction added successfully! It is now pending blockchain verification.";

            // Add an entry to the Audit Trail
            try {
                $stmt = $pdo->prepare(
                    "INSERT INTO AuditTrail (user_id, activity_title, activity_description, activity_type, activity_status, blockchain_hash)
                     VALUES (:user_id, :activity_title, :activity_description, :activity_type, :activity_status, :blockchain_hash)"
                );
                $auditTitle = "New Transaction Added";
                $auditDesc = "Transaction '{$description}' with amount {$amount} {$currency} added and pending blockchain verification.";
                $activityType = "Transactions";
                $activityStatus = "Pending";

                $stmt->bindParam(':user_id', $userId, PDO::PARAM_INT);
                $stmt->bindParam(':activity_title', $auditTitle);
                $stmt->bindParam(':activity_description', $auditDesc);
                $stmt->bindParam(':activity_type', $activityType);
                $stmt->bindParam(':activity_status', $activityStatus);
                $stmt->bindParam(':blockchain_hash', $blockchainHash);
                $stmt->execute();
            } catch (PDOException $e) {
                error_log("Error logging audit trail for new transaction: " . $e->getMessage());
            }

            // Clear form fields after successful submission
            $_POST = array(); // Clear POST data to reset form
        } else {
            $errorMessage = "Failed to add transaction. Please try again.";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Transaction | AccountAble</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --primary-color: #2e7d32; /* Deep green */
            --primary-dark: #1b5e20; /* Darker green */
            --primary-light: #4caf50; /* Lighter green */
            --accent-color: #8bc34a; /* Lime green accent */
            --dark-color: #212121; /* Dark gray/black */
            --light-color: #f5f5f5; /* Light gray */
            --text-dark: #333333;
            --text-light: #ffffff;
            --gray-color: #757575;
            --success-color: #4caf50;
            --warning-color: #ff9800;
            --danger-color: #f44336;
            --shadow-sm: 0 2px 5px rgba(0,0,0,0.1);
            --shadow-md: 0 4px 10px rgba(0,0,0,0.15);
            --shadow-lg: 0 8px 20px rgba(0,0,0,0.2);
            --transition: all 0.3s ease;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', 'Roboto', 'Helvetica Neue', sans-serif;
        }

        body {
            background-color: #f9f9f9;
            color: var(--text-dark);
            display: grid;
            grid-template-columns: 240px 1fr;
            min-height: 100vh;
        }

        /* Sidebar Styles - Reused from dashboard */
        .sidebar {
            background-color: var(--dark-color);
            color: var(--text-light);
            height: 100vh;
            position: sticky;
            top: 0;
            overflow-y: auto;
        }

        .sidebar-header {
            padding: 1.5rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .logo {
            display: flex;
            align-items: center;
            font-size: 1.3rem;
            font-weight: 700;
            color: var(--text-light);
        }

        .logo i {
            margin-right: 0.75rem;
            color: var(--accent-color);
        }

        .nav-menu {
            padding: 1.5rem 0;
        }

        .menu-title {
            padding: 0 1.5rem 0.5rem;
            font-size: 0.8rem;
            text-transform: uppercase;
            color: rgba(255, 255, 255, 0.5);
            letter-spacing: 0.5px;
        }

        .nav-item {
            display: flex;
            align-items: center;
            padding: 0.8rem 1.5rem;
            color: rgba(255, 255, 255, 0.8);
            text-decoration: none;
            transition: var(--transition);
            cursor: pointer;
        }

        .nav-item i {
            margin-right: 1rem;
            width: 20px;
            text-align: center;
        }

        .nav-item:hover, .nav-item.active {
            background-color: rgba(255, 255, 255, 0.1);
            color: var(--text-light);
            border-left: 3px solid var(--accent-color);
        }

        .nav-item.active {
            background-color: rgba(255, 255, 255, 0.05);
        }

        /* Main Content Styles */
        .main-content {
            padding: 2rem;
        }

        /* Header */
        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 2rem;
        }

        .page-title h1 {
            font-size: 1.8rem;
            color: var(--dark-color);
        }

        .page-title p {
            color: var(--gray-color);
            font-size: 0.9rem;
        }

        .user-menu {
            display: flex;
            align-items: center;
            gap: 1.5rem;
        }

        .user-avatar {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid var(--primary-light);
        }

        .user-name {
            font-weight: 600;
        }

        .user-role {
            font-size: 0.8rem;
            color: var(--gray-color);
        }

        /* Form Card */
        .form-card {
            background-color: white;
            border-radius: 10px;
            padding: 2rem;
            box-shadow: var(--shadow-md);
            max-width: 700px;
            margin: 0 auto; /* Center the card */
        }

        .form-card-header {
            margin-bottom: 1.5rem;
            text-align: center;
        }

        .form-card-header h2 {
            font-size: 1.5rem;
            color: var(--dark-color);
            margin-bottom: 0.5rem;
        }

        .form-card-header p {
            color: var(--gray-color);
            font-size: 0.95rem;
        }

        .form-group {
            margin-bottom: 1.25rem;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: 500;
            color: var(--dark-color);
            font-size: 0.95rem;
        }

        .form-control, .form-select, .form-textarea {
            width: 100%;
            padding: 0.75rem 1rem;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            font-size: 0.95rem;
            transition: var(--transition);
        }

        .form-control:focus, .form-select:focus, .form-textarea:focus {
            outline: none;
            border-color: var(--primary-light);
            box-shadow: 0 0 0 3px rgba(76, 175, 80, 0.2);
        }

        .form-textarea {
            resize: vertical;
            min-height: 80px;
        }

        .form-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1.5rem;
        }

        @media (max-width: 768px) {
            .form-grid {
                grid-template-columns: 1fr;
            }
        }

        .btn-submit {
            width: 100%;
            padding: 0.85rem;
            background-color: var(--primary-color);
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: var(--transition);
            margin-top: 1.5rem;
        }

        .btn-submit:hover {
            background-color: var(--primary-dark);
            transform: translateY(-2px);
            box-shadow: var(--shadow-sm);
        }

        .btn-submit:active {
            transform: translateY(0);
        }

        .message-box {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
            font-size: 0.95rem;
        }

        .message-box.success {
            background-color: #e8f5e9;
            color: var(--success-color);
            border: 1px solid var(--success-color);
        }

        .message-box.error {
            background-color: #ffebee;
            color: var(--danger-color);
            border: 1px solid var(--danger-color);
        }

        /* Responsive adjustments for sidebar */
        @media (max-width: 992px) {
            body {
                grid-template-columns: 1fr;
            }

            .sidebar {
                height: auto;
                position: static;
            }
        }
        @media (max-width: 768px) {
            .dashboard-header {
                flex-direction: column;
                align-items: flex-start;
                gap: 1rem;
            }
            .user-menu {
                width: 100%;
                justify-content: space-between;
            }
        }
        @media (max-width: 576px) {
            .main-content {
                padding: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <!-- Sidebar Navigation -->
    <aside class="sidebar">
        <div class="sidebar-header">
            <div class="logo">
                <i class="fas fa-check-double"></i>
                <span>AccountAble</span>
            </div>
        </div>
        <nav class="nav-menu">
            <div class="menu-title">Main</div>
            <a href="udashboard.php" class="nav-item">
                <i class="fas fa-home"></i>
                <span>Dashboard</span>
            </a>
            <a href="Transactions.php" class="nav-item active">
                <i class="fas fa-exchange-alt"></i>
                <span>Transactions</span>
            </a>
            <a href="invoices.php" class="nav-item">
                <i class="fas fa-file-invoice-dollar"></i>
                <span>Invoices</span>
            </a>
            <a href="client.php" class="nav-item">
                <i class="fas fa-users"></i>
                <span>Clients</span>
            </a>
            <a href="Audit-Trail.php" class="nav-item">
                <i class="fas fa-shield-alt"></i>
                <span>Audit Trail</span>
            </a>
            <a href="Verification.php" class="nav-item">
                <i class="fas fa-fingerprint"></i>
                <span>Verification</span>
            </a>

            <div class="menu-title">Account</div>
            <a href="settings.php" class="nav-item">
                <i class="fas fa-cog"></i>
                <span>Settings</span>
            </a>
            <a href="Logout.php" class="nav-item">
                <i class="fas fa-sign-out-alt"></i>
                <span>Logout</span>
            </a>
        </nav>
    </aside>

    <!-- Main Content -->
    <main class="main-content">
        <!-- Dashboard Header -->
        <header class="dashboard-header">
            <div class="page-title">
                <h1>Add New Transaction</h1>
                <p>Record a new financial transaction for your records</p>
            </div>
            <div class="user-menu">
                <div class="user-profile">
                    <img src="https://placehold.co/40x40/2e7d32/ffffff?text=<?php echo substr($currentUser['full_name'], 0, 1); ?>" alt="User" class="user-avatar">
                    <div>
                        <div class="user-name"><?php echo htmlspecialchars($currentUser['full_name']); ?></div>
                        <div class="user-role"><?php echo htmlspecialchars($currentUser['user_role']); ?></div>
                    </div>
                </div>
            </div>
        </header>

        <section class="form-card">
            <div class="form-card-header">
                <h2>Transaction Details</h2>
                <p>Fill in the information below to add a new transaction.</p>
            </div>

            <?php if (!empty($errorMessage)): ?>
                <div class="message-box error"><?php echo htmlspecialchars($errorMessage); ?></div>
            <?php endif; ?>
            <?php if (!empty($successMessage)): ?>
                <div class="message-box success"><?php echo htmlspecialchars($successMessage); ?></div>
            <?php endif; ?>

            <form method="POST" action="add_transaction.php">
                <div class="form-grid">
                    <div class="form-group">
                        <label for="transaction_date">Date</label>
                        <input type="date" id="transaction_date" name="transaction_date" class="form-control" value="<?php echo htmlspecialchars($_POST['transaction_date'] ?? date('Y-m-d')); ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="transaction_type">Type</label>
                        <select id="transaction_type" name="transaction_type" class="form-select" required>
                            <option value="">Select Type</option>
                            <option value="Income" <?php echo (($_POST['transaction_type'] ?? '') == 'Income') ? 'selected' : ''; ?>>Income</option>
                            <option value="Expense" <?php echo (($_POST['transaction_type'] ?? '') == 'Expense') ? 'selected' : ''; ?>>Expense</option>
                            <option value="Transfer" <?php echo (($_POST['transaction_type'] ?? '') == 'Transfer') ? 'selected' : ''; ?>>Transfer</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="category">Category</label>
                        <input type="text" id="category" name="category" class="form-control" placeholder="e.g., Office Supplies, Salary" value="<?php echo htmlspecialchars($_POST['category'] ?? ''); ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="client_id">Client (Optional)</label>
                        <select id="client_id" name="client_id" class="form-select">
                            <option value="">Select Client</option>
                            <?php foreach ($clients as $client): ?>
                                <option value="<?php echo htmlspecialchars($client['client_id']); ?>"
                                    <?php echo ((isset($_POST['client_id']) && $_POST['client_id'] == $client['client_id']) ? 'selected' : ''); ?>>
                                    <?php echo htmlspecialchars($client['client_name']); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="amount">Amount</label>
                        <input type="number" id="amount" name="amount" class="form-control" step="0.01" min="0" placeholder="e.g., 1500.00" value="<?php echo htmlspecialchars($_POST['amount'] ?? ''); ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="currency">Currency</label>
                        <input type="text" id="currency" name="currency" class="form-control" placeholder="e.g., UGX, USD" value="<?php echo htmlspecialchars($_POST['currency'] ?? ($currentUser['default_currency'] ?? 'UGX')); ?>" required>
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" name="description" class="form-textarea" placeholder="Detailed description of the transaction" required><?php echo htmlspecialchars($_POST['description'] ?? ''); ?></textarea>
                </div>

                <button type="submit" class="btn-submit">Add Transaction</button>
            </form>
        </section>
    </main>

    <script>
        // Set active navigation item
        document.addEventListener('DOMContentLoaded', function() {
            const currentPath = window.location.pathname;
            document.querySelectorAll('.nav-item').forEach(item => {
                if (item.href.includes(currentPath.split('/').pop())) {
                    item.classList.add('active');
                }
            });
        });
    </script>
</body>
</html>
